version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless@1.51.0

      - run:
          name: Install Dependencies
          command: npm install

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            sls deploy --stage prod
          elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
            sls deploy --stage dev
          fi

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
